const info = {
    me: {
        name: "Nazmul Haque",
        title: "Full Stack Developer",
        email: "nazmul2018s@gmail.com",
        phone: "+8801917003822",
        experience: "4+ experience",
        image: "/images/person.png",
        linkedin: "https://www.linkedin.com/in/nazzmulhq/",
        github: "https://www.github.com/nazzmulhq",
        resume: "https://www.github.com/nazzmulhq",
    },
    skills: [
        "JavaScript",
        "TypeScript",
        "React.js",
        "Node.js",
        "Express.js",
        "Next.js",
        "Nest.js",
        "Tailwind CSS",
        "Material UI",
        "Ant Design",
        "Docker",
        "Kubernetes",
    ],
    experience: [
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Software Specialist (Fullstack)",
            address: " 27, 1 New Eskaton Road, Dhaka 1000",
            company: "SSL Wireless Ltd.",
            date: "Oct 2023 - Present",
            description: [
                "Lead ERP frontend development using Next.js 14 and TypeScript",
                "Design and implement modular ERP components with Ant Design and TailwindCSS",
                "Create complex state management solutions using Redux Toolkit",
                "Set up automated CI/CD pipelines GitHub Actions for deployment using Docker",
            ],
            technologies: [
                "Next.js 14",
                "TypeScript",
                "Ant Design",
                "TailwindCSS",
                "Docker",
                "Kubernetes",
                "GitHub Actions",
                "Redux Toolkit",
            ],
        },
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Software Engineer (Fullstack)",
            company: "APSIS Ltd.",
            date: "Nov 2022 - Oct 2023",
            address: "Ahmed Tower, 30 Kemal Ataturk Ave, Dhaka 1213",
            description: [
                "Developed enterprise ERP system using Next.js and NestJS",
                "Built scalable RESTful APIs using NestJS with Knex",
                "Implemented responsive UI components using Ant Design and TailwindCSS",
                "Designed and optimized PostgreSQL database schemas for ERP modules",
            ],
            technologies: [
                "Next.js",
                "NestJS",
                "TypeScript",
                "Ant Design",
                "TailwindCSS",
                "PostgreSQL",
                "Redis",
                "Microservices",
            ],
        },
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Software Engineer (Frontend)",
            company: "mPower Social Enterprises Ltd.",
            date: "Nov 2020 - Nov 2022",
            address:
                "Level 10 House 77, Nur Empori, Road 11 Banani Bridge, Dhaka 1213",
            description: [
                "Led frontend development using React.js and TypeScript for enterprise applications",
                "Created reusable component libraries and established frontend architecture",
                "Conducted requirement analysis and created detailed technical specifications",
                "Designed RESTful API integrations and state management using Redux",
            ],
            technologies: [
                "React.js",
                "TypeScript",
                "Material-UI",
                "Redux",
                "Jest",
                "REST APIs",
                "Git",
                "Agile/Scrum",
            ],
        },
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Associate Software Engineer",
            address: "Komlapur, Dhaka",
            company: "ROTech Ltd.",
            date: "Jul 2020 - Nov 2020",
            description: [
                "Developed backend APIs using Python Django frameworks with RESTful architecture",
                "Designed ERP Module and implemented & responsive frontend using HTML5, CSS3, and JavaScript",
                "Conducted requirement analysis and created detailed technical specifications",
                "Designed and optimized PostgreSQL database schemas and queries",
            ],
            technologies: [
                "Python",
                "Django",
                "HTML5/CSS3",
                "JavaScript",
                "PostgreSQL",
                "Git",
                "RESTful APIs",
            ],
        },
    ],
    education: [
        {
            title: "Daffodil International University",
            degree: "Bachelor of Science in Computer Science and Engineering",
            date: "2016 - 2020",
        },
        {
            title: "Meherpur College of Engineering & Technology",
            degree: "Diploma-in-Computer Engineering",
            date: "2012 - 2016",
        },
        {
            title: "Kobi Nazrul Shikkha Manzil",
            degree: "Secondary School Certificate",
            date: "2010 - 2012",
        },
    ],
    works: [
        {
            imageOrVideo: "/videos/project/lms.png",
            title: "Quick Dockerize Tool",
            technologies: ["JavaScript", "Node.js", "Shell Script"],
            description: [
                "Developed a CLI tool to quickly dockerize any Node.js or Php project",
                "Automatically generates Dockerfile and docker-compose.yml files",
                "Allows to choose between Node.js or Php and the version",
            ],
            link: "https://www.npmjs.com/package/quick-cicd",
        },
        {
            imageOrVideo: "/videos/project/lms.mp4",
            title: "E-Learning Platform",
            technologies: ["React.js", "Laravel", "TailwindCSS", "MySQL"],
            description: [
                "Figma design analysis and deviated the design into components",
                "Developed the frontend using React.js",
                "Use Redux for state management and RTK Query for API fetching and caching",
            ],
            link: null,
        },
    ],
};

export default info;
