const info = {
    me: {
        name: "Nazmul Haque",
        title: "Senior Software Specialist",
        email: "nazmul2018s@gmail.com",
        phone: "+8809696917752",
        whatsapp: "+8801917003822",
        experience: "4+ years",
        image: "/images/person.png",
        mysite: "https://nazmulhaque.netlify.app/",
        linkedin: "https://www.linkedin.com/in/nazzmulhq/",
        github: "https://www.github.com/nazzmulhq",
        resume: "/doc/Nazmul_Haque_CV.pdf",
    },
    skills: [
        "JavaScript",
        "TypeScript",
        "Python",
        "Go (beginner)",
        "React.js",
        "Next.js",
        "Nest.js",
        "FastAPI",
        "Django",
        "TailwindCSS",
        "Ant Design",
        "Docker",
        "Kubernetes",
        "Microservices",
    ],
    // Grouped view for the home page — the category is information, where a
    // flat list of pills is just decoration.
    skillGroups: [
        { label: "Languages", items: ["TypeScript", "JavaScript", "Python", "Go (beginner)"] },
        { label: "Frontend", items: ["React.js", "Next.js", "Redux Toolkit", "TailwindCSS", "Ant Design"] },
        { label: "Backend", items: ["Nest.js", "FastAPI", "Django", "REST APIs", "Microservices"] },
        { label: "Data", items: ["PostgreSQL", "MySQL", "MongoDB", "Redis"] },
        { label: "Infrastructure", items: ["Docker", "Kubernetes", "GitHub Actions", "CI/CD"] },
    ],
    experience: [
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Senior Software Specialist",
            address: "Borak Zahir Tower, Kawran Bazar, Dhaka 1205",
            company: "SSL Wireless Ltd.",
            date: "Jan 2026 - Present",
            description: [
                "Spearhead full-stack ERP development using Next.js 16, NestJS, and TypeScript.",
                "Architect scalable frontend components with Ant Design and TailwindCSS.",
                "Design NestJS backend APIs with RESTful integration and Redux Toolkit.",
                "Establish CI/CD pipelines using GitHub Actions, Docker, and Kubernetes.",
            ],
            problemSolved: "Cut ERP deployment times from hours to minutes and built a no-code E-commerce Builder for non-technical teams.",
            technologies: [
                "Next.js 16",
                "NestJS",
                "TypeScript",
                "Ant Design",
                "TailwindCSS",
                "Docker",
                "Kubernetes",
                "GitHub Actions",
                "Redux Toolkit",
            ],
        },
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Software Specialist",
            address: "Borak Zahir Tower, Kawran Bazar, Dhaka 1205",
            company: "SSL Wireless Ltd.",
            date: "Oct 2023 - Dec 2025",
            description: [
                "Deliver full-stack ERP solutions using Next.js 14, NestJS, and TypeScript.",
                "Design modular, reusable frontend components with Ant Design and TailwindCSS.",
                "Develop NestJS backend APIs and integrate third-party services with Redux Toolkit.",
                "Configure CI/CD pipelines with GitHub Actions and Docker for production deployment.",
            ],
            problemSolved: "Built a production planning solution with a modular architecture, cutting UI render times by 40%.",
            technologies: [
                "Next.js 14",
                "NestJS",
                "TypeScript",
                "Ant Design",
                "TailwindCSS",
                "Docker",
                "Kubernetes",
                "GitHub Actions",
                "Redux Toolkit",
            ],
        },
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Software Engineer",
            company: "APSIS Ltd.",
            date: "Nov 2022 - Oct 2023",
            address: "Ahmed Tower, 30 Kemal Ataturk Ave, Dhaka 1213",
            description: [
                "Delivered full-stack enterprise ERP system with Next.js and NestJS.",
                "Architected scalable RESTful APIs and microservices using NestJS with Knex ORM.",
                "Implemented responsive UI components using Ant Design and TailwindCSS.",
                "Designed and optimized PostgreSQL database schemas and queries for ERP modules.",
            ],
            problemSolved: "Delivered a banking solution for IFIC, refactoring schemas to remove deadlocks and speed up queries by 300%.",
            technologies: [
                "Next.js",
                "NestJS",
                "TypeScript",
                "Ant Design",
                "TailwindCSS",
                "PostgreSQL",
                "Redis",
                "Microservices",
            ],
        },
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Software Engineer",
            company: "mPower Social Enterprises Ltd.",
            date: "Nov 2021 - Nov 2022",
            address:
                "Level 10 House 77, Nur Empori, Road 11 Banani Bridge, Dhaka 1213",
            description: [
                "Led frontend development of enterprise applications using React.js and TypeScript.",
                "Built and maintained reusable component libraries with Material-UI and custom design systems.",
                "Established frontend architecture standards and Redux state management patterns.",
                "Conducted requirement analysis and produced detailed technical specifications.",
            ],
            problemSolved: "Built an LMS and agriculture platform on a unified component library, halving feature development time.",
            technologies: [
                "React.js",
                "NestJS",
                "TypeScript",
                "Material-UI",
                "Redux",
                "Jest",
                "REST APIs",
                "Git",
                "Agile/Scrum",
            ],
        },
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Associate Software Engineer",
            address: "Komlapur, Dhaka",
            company: "ROTech Ltd.",
            date: "Jul 2021 - Nov 2021 (Internship)",
            description: [
                "Delivered full-stack ERP modules using Python Django and JavaScript frontend.",
                "Developed RESTful APIs using Python and Django REST framework.",
                "Implemented responsive frontend with HTML5, CSS3, and JavaScript.",
                "Designed and optimized PostgreSQL database schemas and performant queries.",
            ],
            problemSolved: "Automated textile material data-entry workflows, saving operations teams 20+ hours per week.",
            technologies: [
                "Python",
                "Django",
                "HTML5/CSS3",
                "JavaScript",
                "PostgreSQL",
                "Git",
                "RESTful APIs",
            ],
        },
    ],
    education: [
        {
            title: "Daffodil International University",
            for_pdf_title: "Daffodil International University",
            degree: "Bachelor of Science in Computer Science and Engineering",
            for_pdf_degree: "B.Sc. in CSE",
            date: "2016 - 2020",
        },
        {
            title: "Meherpur College of Engineering & Technology",
            for_pdf_title: "Meherpur College of Eng. & Tech.",
            degree: "Diploma in Computer Engineering",
            for_pdf_degree: "Diploma in Computer Engineering",
            date: "2012 - 2016",
        },
        {
            title: "Kobi Nazrul Shikkha Manzil",
            for_pdf_title: "Kobi Nazrul Shikkha Manzil",
            degree: "Secondary School Certificate",
            for_pdf_degree: "SSC",
            date: "2010 - 2012",
        },
    ],
    works: [
        {
            imageOrVideo: "/images/quickdb.png",
            title: "VS Code Extension — QuickDB",
            technologies: [
                "TypeScript",
                "VS Code API",
                "Node.js",
                "SQL",
                "MongoDB",
                "Redis",
            ],
            description: [
                "DataGrip-inspired database management extension for Visual Studio Code.",
                "Browse tables, run queries, manage schemas, and visualize ERDs from the editor.",
                "Supports SQLite, MySQL, PostgreSQL, MongoDB, and Redis with MCP server integration.",
            ],
            link: "/quickdb",
        },
        {
            // Internal enterprise system — no public URL or screenshot to link/show.
            title: "Enterprise ERPs (Textile)",
            technologies: ["React.js", "Redux", "TailwindCSS", "Ant Design", "REST APIs"],
            description: [
                "Currently spearheading full-stack ERP development for textile industry operations, including Production Planning, Manufacturing, and Inventory modules.",
                "Building scalable frontends with React.js, Redux, TailwindCSS, and Ant Design.",
                "Designing and implementing robust RESTful APIs.",
            ],
        },
        {
            imageOrVideo: "/images/zcommerz.jpg",
            title: "Built Zcommerz (E-commerce SaaS)",
            technologies: ["Next.js", "Nest.js"],
            description: [
                "Engineered a comprehensive e-commerce builder platform (zcommerz.com).",
                "Architected an optimized onboarding flow that empowers merchants to launch fully functional online shops in just 5 minutes.",
            ],
            link: "https://zcommerz.com",
        },
        {
            imageOrVideo: "/images/ssl-lms.png",
            title: "SSL Wireless LMS (E-Learning SaaS)",
            technologies: ["Next.js", "Nest.js"],
            description: ["Built a SaaS e-learning platform for SSL Wireless."],
            link: "https://lms.sslwireless.com/",
        },
    ],
};

export default info;
