const info = {
    me: {
        name: "Nazmul Haque",
        title: "Senior Software Specialist",
        email: "nazmul2018s@gmail.com",
        phone: "+8801917003822",
        experience: "4+ years",
        image: "/images/person.png",
        mysite: "https://nazmulhaque.netlify.app/",
        linkedin: "https://www.linkedin.com/in/nazzmulhq/",
        github: "https://www.github.com/nazzmulhq",
        resume: "/doc/Nazmul_Haque_CV.pdf",
    },
    skills: [
        "JavaScript",
        "TypeScript",
        "Python",
        "React.js",
        "Next.js",
        "Nest.js",
        "Django",
        "TailwindCSS",
        "Ant Design",
        "Docker",
        "Kubernetes",
        "Microservices",
    ],
    experience: [
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Senior Software Specialist",
            address: "Borak Zahir Tower, Kawran Bazar, Dhaka 1205",
            company: "SSL Wireless Ltd.",
            date: "Jan 2026 - Present",
            description: [
                "Spearhead full-stack ERP development using Next.js 16, NestJS, and TypeScript.",
                "Architect scalable frontend components with Ant Design and TailwindCSS.",
                "Design NestJS backend APIs with RESTful integration and Redux Toolkit.",
                "Establish CI/CD pipelines using GitHub Actions, Docker, and Kubernetes.",
            ],
            problemSolved: "Modernized legacy ERP infrastructure, reducing deployment times from hours to minutes and significantly improving system scalability under high load.",
            technologies: [
                "Next.js 16",
                "NestJS",
                "TypeScript",
                "Ant Design",
                "TailwindCSS",
                "Docker",
                "Kubernetes",
                "GitHub Actions",
                "Redux Toolkit",
            ],
        },
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Software Specialist",
            address: "Borak Zahir Tower, Kawran Bazar, Dhaka 1205",
            company: "SSL Wireless Ltd.",
            date: "Oct 2023 - Dec 2025",
            description: [
                "Deliver full-stack ERP solutions using Next.js 14, NestJS, and TypeScript.",
                "Design modular, reusable frontend components with Ant Design and TailwindCSS.",
                "Develop NestJS backend APIs and integrate third-party services with Redux Toolkit.",
                "Configure CI/CD pipelines with GitHub Actions and Docker for production deployment.",
            ],
            problemSolved: "Resolved severe frontend bottlenecks by implementing modular architectures and robust state management, cutting UI render times by 40%.",
            technologies: [
                "Next.js 14",
                "NestJS",
                "TypeScript",
                "Ant Design",
                "TailwindCSS",
                "Docker",
                "Kubernetes",
                "GitHub Actions",
                "Redux Toolkit",
            ],
        },
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Software Engineer",
            company: "APSIS Ltd.",
            date: "Nov 2022 - Oct 2023",
            address: "Ahmed Tower, 30 Kemal Ataturk Ave, Dhaka 1213",
            description: [
                "Delivered full-stack enterprise ERP system with Next.js and NestJS.",
                "Architected scalable RESTful APIs and microservices using NestJS with Knex ORM.",
                "Implemented responsive UI components using Ant Design and TailwindCSS.",
                "Designed and optimized PostgreSQL database schemas and queries for ERP modules.",
            ],
            problemSolved: "Refactored inefficient database schemas, eliminating deadlocks and accelerating complex enterprise analytical queries by up to 300%.",
            technologies: [
                "Next.js",
                "NestJS",
                "TypeScript",
                "Ant Design",
                "TailwindCSS",
                "PostgreSQL",
                "Redis",
                "Microservices",
            ],
        },
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Software Engineer",
            company: "mPower Social Enterprises Ltd.",
            date: "Nov 2021 - Nov 2022",
            address:
                "Level 10 House 77, Nur Empori, Road 11 Banani Bridge, Dhaka 1213",
            description: [
                "Led frontend development of enterprise applications using React.js and TypeScript.",
                "Built and maintained reusable component libraries with Material-UI and custom design systems.",
                "Established frontend architecture standards and Redux state management patterns.",
                "Conducted requirement analysis and produced detailed technical specifications.",
            ],
            problemSolved: "Tackled immense technical debt by architecting a unified component library, which halved the time required for new feature development.",
            technologies: [
                "React.js",
                "NestJS",
                "TypeScript",
                "Material-UI",
                "Redux",
                "Jest",
                "REST APIs",
                "Git",
                "Agile/Scrum",
            ],
        },
        {
            icon: "https://img.icons8.com/ios/50/000000/react-native.png",
            title: "Associate Software Engineer",
            address: "Komlapur, Dhaka",
            company: "ROTech Ltd.",
            date: "Jul 2021 - Nov 2021 (Internship)",
            description: [
                "Delivered full-stack ERP modules using Python Django and JavaScript frontend.",
                "Developed RESTful APIs using Python and Django REST framework.",
                "Implemented responsive frontend with HTML5, CSS3, and JavaScript.",
                "Designed and optimized PostgreSQL database schemas and performant queries.",
            ],
            problemSolved: "Automated deeply manual data-entry workflows by building intuitive client interfaces, saving operations teams over 20 hours per week.",
            technologies: [
                "Python",
                "Django",
                "HTML5/CSS3",
                "JavaScript",
                "PostgreSQL",
                "Git",
                "RESTful APIs",
            ],
        },
    ],
    education: [
        {
            title: "Daffodil International University",
            for_pdf_title: "Daffodil International University",
            degree: "Bachelor of Science in Computer Science and Engineering",
            for_pdf_degree: "B.Sc. in CSE",
            date: "2016 - 2020",
        },
        {
            title: "Meherpur College of Engineering & Technology",
            for_pdf_title: "Meherpur College of Eng. & Tech.",
            degree: "Diploma in Computer Engineering",
            for_pdf_degree: "Diploma in Computer Engineering",
            date: "2012 - 2016",
        },
        {
            title: "Kobi Nazrul Shikkha Manzil",
            for_pdf_title: "Kobi Nazrul Shikkha Manzil",
            degree: "Secondary School Certificate",
            for_pdf_degree: "SSC",
            date: "2010 - 2012",
        },
    ],
    works: [
        {
            imageOrVideo: "/images/quickdb.png",
            title: "VS Code Extension — QuickDB",
            technologies: [
                "TypeScript",
                "VS Code API",
                "Node.js",
                "SQL",
                "MongoDB",
                "Redis",
            ],
            description: [
                "DataGrip-inspired database management extension for Visual Studio Code.",
                "Browse tables, run queries, manage schemas, and visualize ERDs from the editor.",
                "Supports SQLite, MySQL, PostgreSQL, MongoDB, and Redis with MCP server integration.",
            ],
            link: "/quickdb",
        },
        {
            imageOrVideo: "/images/quick-cicd.png",
            title: "Quick Dockerize Tool",
            technologies: ["JavaScript", "Node.js", "Shell Script"],
            description: [
                "Developed CLI tool for rapid containerization of Node.js and PHP projects.",
                "Automatically generates production-ready Dockerfile and docker-compose.yml.",
                "Provides interactive selection of runtime (Node.js/PHP) and version management.",
            ],
            link: "/quick-cicd",
        },
        {
            imageOrVideo: "/images/eslint-prettier-nextjs.jpg",
            title: "ESLint & Prettier Setup for Next.js",
            technologies: ["JavaScript", "Node.js", "Shell Script"],
            description: [
                "Published npm package for automated ESLint and Prettier configuration in Next.js.",
                "Handles dependency installation and config generation with zero manual setup.",
                "Supports both TypeScript and JavaScript project configurations.",
            ],
            link: "https://www.npmjs.com/package/nextjs-eslint-prettier-setup",
        },
        {
            imageOrVideo: "/images/quick-design-system.jpg",
            title: "Quick UI Design",
            technologies: ["Next.js", "Ant Design", "TypeScript"],
            description: [
                "Scaffolding tool for rapid web application UI development with Ant Design and Next.js.",
                "Delivers reusable component libraries and responsive layout templates.",
                "Supports TypeScript and JavaScript with configurable project structure.",
            ],
            link: "https://www.npmjs.com/package/quick-ui-design",
        },
    ],
};

export default info;
